import type { Metadata } from 'next';
import { Kalam } from 'next/font/google';
import './globals.css';

const kalam = Kalam({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={kalam.className}>{children}</body>
        </html>
    );
}
